### ISSUE TITLE
Can't share image

### ISSUE THREAD

**Issue by fg2q1q3q** [tvbarthel/IntentShare#32]
Hello, I am a Chinese developer, I found that can only share text, pictures can not be shared when I share to  Sina weibo(com.sina.weibo)/Tencent QQ(com.tencent.mobileqq)/WeChat(com.tencent.mm) with IntentShare,please help me!

**Comment by tbarthel-fr** [comment]
Hi @fg2q1q3q (=

Thanks for your interest in our project.

We are going to look at your issue as soon as possible.

The default FileProvider for image from the support library was causing issues for the Messaging app (com.android.messsaging) #30  It might be a similar issue for the apps you listed.

We are going to have a look and we will come back to you asap (:

**Comment by fg2q1q3q** [comment]
ok,thanks,I will continue to focus on dynamic updates

**Comment by tbarthel-fr** [comment]
Hi @fg2q1q3q (=

We have just check the behavior for the WeChat app (com.tencent.mm) and it seems like WeChat doesn't handle native ACTION_SEND extras as expected :

Extra:(Text, Subject) => Text displayed in the WeChat sharing dialog, subject ignore since WeChat isn't a mail client. 👍 

![screenshot_20160513-082125](https://cloud.githubusercontent.com/assets/4211470/15239861/03ceb28a-18e6-11e6-849e-c474e122fd00.png)

![screenshot_20160513-082140](https://cloud.githubusercontent.com/assets/4211470/15239860/03bd4c7a-18e6-11e6-9576-cf997fbe3b74.png)

![screenshot_20160513-084208](https://cloud.githubusercontent.com/assets/4211470/15240014/0436408e-18e7-11e6-9c6e-790b98d2026a.png)

![screenshot_20160513-084255](https://cloud.githubusercontent.com/assets/4211470/15240019/0a3fb4f6-18e7-11e6-8f5c-2d21808f7c86.png)

Working 👍 

---

Extra:(Text,Subject,Image) => Image displayed in the WeChat sharing dialog but the text is missing. Once shared in a channel, neither image nor text are send... 👎 

![screenshot_20160513-082151](https://cloud.githubusercontent.com/assets/4211470/15239858/03bc4e92-18e6-11e6-9f15-a79eac557151.png)

![screenshot_20160513-082201](https://cloud.githubusercontent.com/assets/4211470/15239862/03d4751c-18e6-11e6-8865-934928672444.png)

![screenshot_20160513-084208](https://cloud.githubusercontent.com/assets/4211470/15240062/4cdbc32c-18e7-11e6-85cd-0d599d1a43bc.png)

![screenshot_20160513-084214](https://cloud.githubusercontent.com/assets/4211470/15240072/5b424f08-18e7-11e6-8a82-11230b0e5795.png)

Not working 👎 Nothing added in the channel, neither text nor image.

---

Extra:(Image) => "Forward to" displayed in the WeChat sharing dialog. Once send clicked, "Sending image"  dialog displayed in the WeChat app and the image is well send in the selected channel. 👍 

![screenshot_20160513-082509](https://cloud.githubusercontent.com/assets/4211470/15239859/03bc5c98-18e6-11e6-8708-4bee12db5672.png)

![screenshot_20160513-084313](https://cloud.githubusercontent.com/assets/4211470/15240092/74ee75bc-18e7-11e6-8b6e-3d3c1dea1b5a.png)

![screenshot_20160513-084316](https://cloud.githubusercontent.com/assets/4211470/15240098/7af0924c-18e7-11e6-9019-0f5a19f54878.png)

![screenshot_20160513-084320](https://cloud.githubusercontent.com/assets/4211470/15240101/8093b652-18e7-11e6-8567-81848f37b32e.png)

Working 👍 

---

WeChat app seems to not handle native Intent.ACTION_SEND has expected when both EXTRA_TEXT as well as EXTRA_STREAM are present. Therefore, you will have to distinguish image and text sharing and use two different ExtraProvider for these two different sharing use-cases until we find something to bypass this issue.

Currently it seems to be more an issue on WeChat app than on IntentShare side but we are going to analyse a little bit more to check if we could change these unexpected behaviour by tweaking the intent type.

Stay tunned.

**Comment by fg2q1q3q** [comment]
OK, thank you very much, This is indeed a solution to deal with  two different ExtraProvider!

**Comment by tbarthel-fr** [comment]
Hi @fg2q1q3q (=

We tried to play with the mimeType of ACTION_SEND intent but nothing provide the expected behavior for the WeChat app. It seems like WeChat app isn't compliant with ACTION_SEND providing both EXTRA_TEXT and EXTRA_STREAM. Fortunately, IntentShare will allow you to provide a specific provider for WeChat extras and keep a full experience for other app which are fully compliant with the ACTION_SEND spec (=

Stay us tuned if you have other questions (:

Happy coding,

Thomas.

**Comment by lilac** [comment]
Hi, could you share how do you make the ACTION_SEND with text working, although you mentioned it is not compliant? I wonder what intent extras have you supplied to make it working.
