### ISSUE TITLE
Twitter post character limit

### ISSUE THREAD

**Issue by petitTrung** [tvbarthel/IntentShare#39]
Hello,

Actually there is a limit exception in `IntentShare` class.

According to Twitter : https://blog.twitter.com/2016/doing-more-with-140-characters (section "Tweet object changes") 

**"...Developers must avoid hard-coding length assumptions into their applications."**

I think it's better that we remove the following Exception in `IntentShare` : 

```java
if (tweet.length() > 140) {
            throw new IllegalArgumentException("Invalid tweet content : "
                    + "exceed the 140-Character limit : " + tweet);
}
``` 

We could not know if Twitter API will be changed in other ways so let Twitter application manages the sharing text.

What do you think?

Thanks.

**Comment by tbarthel-fr** [comment]
Hi @petitTrung (=

Thanks for pointing this out!

Regarding their article, I think it doesn't make sense to check the length at this level anymore.

It's kinda sad since the idea was to avoid user deleting half of the shared text for client which doesn't respect the limit. But since proper check can't be performed, it must be removed I guess.

The link you mentioned might be added to the javadoc in order to let developers handle the length on their side.

The fix has been added to the road map, might be live asap.

Thanks again!
