### ISSUE TITLE
Support android 14

### ISSUE THREAD

**Issue by tellfa** [tvbarthel/IntentShare#43]
Please add support android 14+

**Comment by petitTrung** [comment]
@tellfa : API 14/15 represents a tiny distribution according to Google (Novembre 2016) 

https://developer.android.com/about/dashboards/index.html

* Globally I do not see anything which restricts the usage of API 14 in the library so you can clone the project, downgrade minSDK to 14 and compile, then copy .aar to your own project.

Happy coding.

**Comment by tbarthel-fr** [comment]
Hi @tellfa (=

Thanks for your feedback. 

This project must already support android 14+ but minSdk was 16.

I have just submitted a new update #44 

A new version of the library might be live during the weekend. On your side, you can already use the last version (v0.0.3) and override the minSdk in order to allow you to compile in minSdk 14:
```xml
<manifest package="..."
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools">

    <uses-sdk tools:overrideLibrary="fr.tvbarthel.intentshare.loader.picasso, fr.tvbarthel.intentshare, fr.tvbarthel.intentshare.loader.glide"/>

...

</manifest>
```

Sorry for the inconvenience.

**Comment by tbarthel-fr** [comment]
@tellfa thanks for your interest in our project (=

Thanks to you, the minSdk is now 14:

```compile 'fr.tvbarthel.intentshare:library:0.0.4'```

Have a nice day and happy coding (:
